In [4]:
import numpy as np
pylist=[1,2,3,4,5]
print(type(pylist))
a=np.array(pylist)  #converts to a list to ndarray
print(a,type(a))

<class 'list'>
[1 2 3 4 5] <class 'numpy.ndarray'>


In [15]:
b=np.array([[1,2,5],
            [6,7,8],
           [9,10,11]])
print(b)

[[ 1  2  5]
 [ 6  7  8]
 [ 9 10 11]]


In [21]:
b[0][1]

2

In [28]:
c=np.array([[0.,0.,0.,],
           [1.,1.,1.,],
           [2.,2.,2.,]])
print(c)
c.shape

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]]


(3, 3)

In [34]:
# np.zeros(5)  #1D array initialise with 0
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [33]:
np.zeros((2,3,4))


array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [36]:
# np.zeros?
np.empty?  #initialise empty array with random values

In [37]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [38]:
arr=np.array([2,121,24,123,43])
np.sort(arr)

array([  2,  24,  43, 121, 123])

In [ ]:
#concatenate array